-- File: HelloWorld.vhd
-- Generated by MyHDL 0.11.45
-- Date: Fri May  3 00:37:15 2024


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity HelloWorld is
end entity HelloWorld;


architecture MyHDL of HelloWorld is



signal clk: std_logic;

begin




HELLOWORLD_DRIVE_CLK: process is
begin
    while True loop
        clk <= stdl((not bool(clk)));
        wait for 10 * 1 ns;
    end loop;
    wait;
end process HELLOWORLD_DRIVE_CLK;

HELLOWORLD_SAY_HELLO: process (clk) is
    variable L: line;
begin
    if rising_edge(clk) then
        write(L, string'("Hello World!"));
        writeline(output, L);
    end if;
end process HELLOWORLD_SAY_HELLO;

end architecture MyHDL;
