-- File: Python_Example.vhd
-- Generated by MyHDL 0.11.45
-- Date: Thu May  2 23:49:53 2024


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity Python_Example is
    port (
        clk_i: in std_logic;
        led_o: out std_logic
    );
end entity Python_Example;


architecture MyHDL of Python_Example is



signal cnt: unsigned(22 downto 0);
signal tgl: std_logic;

begin




PYTHON_EXAMPLE_COUNTER: process (clk_i) is
begin
    if rising_edge(clk_i) then
        if (signed(resize(cnt, 24)) = (6000000 - 1)) then
            tgl <= (not tgl);
            led_o <= tgl;
            cnt <= to_unsigned(0, 23);
        else
            cnt <= (cnt + 1);
        end if;
    end if;
end process PYTHON_EXAMPLE_COUNTER;

end architecture MyHDL;
